markdown: rdiscount
permalink: /:title/
url: phoeker.github.io
name: OXI
author: OXI
qq: 1575057492
email: 1575057492@qq.com
duoshuo: oxi
beian: 浙ICP备xxxx号
cnzz: nil
weibo: nil
github: phoeker
pygments: true
safe: true
paginate: 20
about: "这里是 oxi 的个人博客，创建于 2015 年。切换到分类模可以更快地找到感兴趣的内容，欢迎观赏、建议、拍砖……"
